import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import ClientWrapper from "@/components/client-wrapper";
import FloatingActions from "@/components/contact-buttons";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased`}
      >
        
        <Navbar />
        <ClientWrapper />
        {children}
        <FloatingActions />
        <Footer />
      </body>
    </html>
  );
}
